### ISSUE TITLE
[rpc] server panic

### ISSUE THREAD

**Issue by pause125** [rooch-network/rooch#2247]
Reproducible Steps:

1. Start a local server.
2. Run RPC query: 
```
$ curl '0.0.0.0:6767' -H 'content-type:application/json' --data-raw '{"jsonrpc":"2.0","id":51,"method":"rooch_queryObjectStates","params":[{"object_type":"0x3::coin_store::CoinStore<0x3::gas_coin::GasCoin>"},null,null,{"decode":true,"descending":true}]}'
curl: (52) Empty reply from server
 ```
3. error message in server side:

```shell
2024-07-22T13:18:40.360832Z  INFO rooch_rpc_server::service::rpc_logger: event="on_call" method_name="rooch_queryObjectStates" params="[{\"object_type\":\"0x3::coin_store::CoinStore<0x3::gas_coin::GasCoin>\"},null,null,{\"decode\":true,\"descending\":true}]"
thread 'tokio-runtime-worker' panicked at crates/rooch-types/src/address.rs:664:74:
index out of bounds: the len is 0 but the index is 0
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
2024-07-22T13:18:40.389392Z ERROR rooch_rpc_server: Panic occurred:
 panicked at crates/rooch-types/src/address.rs:664:74:
index out of bounds: the len is 0 but the index is 0
 exit the process
```

**Comment by jolestar** [comment]
It seems like trying to format a default Bitcoin address; it is an empty address.

**Comment by baichuan3** [comment]
The system is still prone to panic. Feel like that it is necessary to restart and provide services normally for certain scenarios, such as RPC calls, even if panic occurs. The only thing I can think of now is that if L1 block and L1 tx fail, the system cannot heal itself; other scenarios should restart and provide services. @jolestar

**Comment by jolestar** [comment]
The docker will auto-restart the progress. But the panic needs to be fixed.
